// This file is released under the 3-clause BSD license. See COPYING-BSD.
// Generated by builder.sce : Please, do not edit this file
// cleaner.sce
// ------------------------------------------------------
curdir = pwd();
cleaner_path = get_file_path('cleaner.sce');
chdir(cleaner_path);
// ------------------------------------------------------
if fileinfo('loader.sce') <> [] then
  mdelete('loader.sce');
end
// ------------------------------------------------------
if fileinfo('libscilab_octave.so') <> [] then
  mdelete('libscilab_octave.so');
end
// ------------------------------------------------------
if fileinfo('libscilab_octave.cpp') <> [] then
  mdelete('libscilab_octave.cpp');
end
// ------------------------------------------------------
if fileinfo('libscilab_octave.hxx') <> [] then
  mdelete('libscilab_octave.hxx');
end
// ------------------------------------------------------
if fileinfo('libscilab_octave.h') <> [] then
  mdelete('libscilab_octave.h');
end
// ------------------------------------------------------
chdir(curdir);
// ------------------------------------------------------
